name: Deploy to LocalStack

on:
  push:
    branches:
      - main
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.4.0'

      - name: Set up LocalStack
        uses: LocalStack/setup-localstack@v1
        with:
          install-awslocal: true
          use-light-image: false
          debug: true

     - name: Esperar a que LocalStack esté listo
  run: |
    until curl -s http://localhost:4566/_localstack/health | grep '"status": "running"'; do
      echo "Esperando a que LocalStack esté listo..."
      sleep 5
    done
    echo "LocalStack está listo"


      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
